
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:13306/unluckyjung
    username: root
    password: asdf

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        show-sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.SQL: trace
#  org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true  # 기본이 true이다. 운영에선 false로 반드시 잡아야한다.
