###
POST http://localhost:8080/api/v1/file/77/attribute?filename="testFilename"
Accept:application/json, text/csv, */*
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="testCsvFile.csv"
Content-Type: multipart/form-data

< test.csv

--boundary
Content-Disposition: form-data; name="name"

goodall

--boundary
Content-Disposition: form-data; name="age"

30
--boundary--
