version: '3.7'

services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    hostname: redis6379
    command: ["redis-server", "--appendonly", "yes"]
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
