version: '3.7'
services:
    redis:
      image: redis:latest
      container_name: redis
      hostname: redis6379
      command: redis-server
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
